name = "EnchantedOasis"
author = "mjra007"
version = "3.0.4-1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ace96ceaac0b285d053ce0b3242618de343862e7e9ab6409248b0c9e898bd4e"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
