name = "EnchantedOasis"
author = "mjra007"
version = "3.0.7-1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7db6c31b4d3838cdfc675e03efe0b17e81995cfba23ccb0cda5335a0c477aa2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
