# This is a basic workflow to help you get started with Actions

name: Curseforge Modpack build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildCurseForge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3 
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with: 
          go-version: '>=1.18.0'
      - run: go version
 
      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest
        
      - name: Build curseforge
        run: packwiz curseforge export 
               
      - name: Read version
        id: modpackVersion
        uses: SebRollen/toml-action@v1.0.0
        with: 
          file: 'pack.toml'
          field: 'version'
          
      - name: Read pack name 
        id: packName
        uses: SebRollen/toml-action@v1.0.0
        with: 
          file: 'pack.toml'
          field: 'name' 
      
      - name: Rename file 
        run: mv "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}.zip" "${{ steps.packName.outputs.value }}CurseForge-${{ steps.modpackVersion.outputs.value }}.zip"
  
  buildTechnicSolder:
    runs-on: ubuntu-latest
    steps:
      - name: Download curseme scripts
        uses: actions/checkout@v3 
        with: 
          repository: mjra007/curseme@master
          
      - run: ./getToken.sh
      
      - name: Download mod jars
        run: ./parsePack.sh "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}.zip" "${{ steps.packName.outputs.value }}CurseForge-${{ steps.modpackVersion.outputs.value }}.zip"
      
      - name: Download TechnicSolder packager
        uses: actions/checkout@v3
        with:
          repository: TechnicSolderPackager
          path: ./packwrk/mods
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name : Build TechnicSolderPackager
        run: "msbuild ./packwrk/mods/TechnicSolderPackager.csproj /p:Configuration=Release /p:Platform=x86 /p:RuntimeIdentifier=linux-x64"
        
      - name: Execute TechnicSolder Packager
        run: ./packwrk/mods/TechnicSolderPackager
      
      
      
  release: 
    runs-on: ubuntu-latest  
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}"
          tag_name: modpacks
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Upload Curseforge artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}.zip"
          asset_name: "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}.zip"
          asset_content_type: application/zip
   
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
