name: Modpack Builds

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  workflow_dispatch:
jobs:
  buildPackFiles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with: 
          go-version: '>=1.18.0'
      - run: go version
 
      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest
        
      - name: Build curseforge
        run: packwiz curseforge export 
               
      - name: Read version
        id: modpackVersion
        uses: SebRollen/toml-action@v1.0.0
        with: 
          file: 'pack.toml'
          field: 'version'
          
      - name: Read pack name 
        id: packName
        uses: SebRollen/toml-action@v1.0.0
        with: 
          file: 'pack.toml'
          field: 'name' 
      
      - name: Rename file 
        run: mv "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}.zip" "${{ steps.packName.outputs.value }}CurseForge-${{ steps.modpackVersion.outputs.value }}.zip"

      - name: Download TechnicSolder packager
        run: | 
          wget https://github.com/mjra007/TechnicSolderPackager/releases/download/ver-dee1afe8a8338e46e94bea6ee356384458a8b93b/technicsolderpackager.zip -P ./
          unzip ./technicsolderpackager.zip
          
      - name: Execute Downloader
        run: dotnet TechnicSolderPackager.dll downloader ${{secrets.CURSEFORGEAPIKEY}}
      
      - name: Execute Packager
        run: dotnet TechnicSolderPackager.dll packager ${{ steps.modpackVersion.outputs.value }} ${{ steps.packName.outputs.value }}TechnicSolder
     
      - name: Setup Chrome 
        uses: browser-actions/setup-chrome@v0.0.0 
        
      - name: setup-chromedriver 
        uses: nanasess/setup-chromedriver@v1.0.7

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "${{ steps.packName.outputs.value }}-${{ steps.modpackVersion.outputs.value }}"
          tag_name: ${{ steps.modpackVersion.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Upload Curseforge artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ steps.packName.outputs.value }}CurseForge-${{ steps.modpackVersion.outputs.value }}.zip"
          asset_name: "${{ steps.packName.outputs.value }}CurseForge-${{ steps.modpackVersion.outputs.value }}.zip"
          asset_content_type: application/zip
      
      - name: Upload TechnicSolder artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ steps.packName.outputs.value }}TechnicSolder-${{ steps.modpackVersion.outputs.value }}.zip"
          asset_name: "${{ steps.packName.outputs.value }}TechnicSolder-${{ steps.modpackVersion.outputs.value }}.zip"
          asset_content_type: application/zip
      
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
            
      - name: Unpack mods for solder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }} 
          script: |
             cd ${{secrets.MODSPATH}}
             curl -LO https://github.com/mjra007/EnchantedOasisModpack/releases/download/${{ steps.modpackVersion.outputs.value }}/${{ steps.packName.outputs.value }}TechnicSolder-${{ steps.modpackVersion.outputs.value }}.zip -P ./
             dotnet TechnicSolderPackager.dll unpacker "${{ steps.packName.outputs.value }}TechnicSolder-${{ steps.modpackVersion.outputs.value }}.zip"
       
      - name: Download NewMods.csv 
        run: wget http://${{ secrets.SERVERIP }}/mods/NewMods.csv
 
      - name: Register Solder mods
        run: dotnet TechnicSolderPackager.dll uploader ${{secrets.SOLDEREMAIL}} ${{secrets.SOLDERPASSWORD}} ${{ secrets.SERVERIP }}
        
#       - name: Upload to CurseForge 
#         uses: itsmeow/curseforge-upload@v3
#         with:
#           token: ${{secrets.CURSEFORGEMODPACKKEY}}
#           project_id: 287738
#           game_endpoint: minecraft 
#           file_path: ${{ steps.packName.outputs.value }}CurseForge-${{ steps.modpackVersion.outputs.value }}.zip  
#           game_versions: 6756 
#           release_type: release
